package com.sdey.impl.mapper;

import java.util.List;

import com.sdey.api.po.HatArea;

public interface HatAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    int insert(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    int insertSelective(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    HatArea selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HatArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HatArea record);

	List<HatArea> getAreasByCityID(String cityID);
}