package com.sdey.impl.mapper;

import java.util.List;

import com.sdey.api.po.HatProvince;

public interface HatProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    int insert(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    int insertSelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    HatProvince selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HatProvince record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hat_province
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HatProvince record);

	List<HatProvince> getAllProvinces();
}