package com.sdey.impl.mapper;

import com.github.pagehelper.Page;
import com.sdey.api.po.Lvfeibaseinfo;
import com.sdey.api.vo.LvfeibaseinfoExport;
import com.sdey.api.vo.SearchInfo;

import java.util.List;

public interface LvfeibaseinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	int insert(Lvfeibaseinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	int insertSelective(Lvfeibaseinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	Lvfeibaseinfo selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Lvfeibaseinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table lvfeibaseinfo
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Lvfeibaseinfo record);

	Page<Lvfeibaseinfo> getDataList();

	Page<Lvfeibaseinfo> search(SearchInfo searchInfo);

	Page<LvfeibaseinfoExport> searchForExport(SearchInfo searchInfo);

	int deleteRowsByIds(List<Integer> collect);
}