package com.sdey.api.po;

public class HatProvince {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.provinceID
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hat_province.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.id
     *
     * @return the value of hat_province.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.id
     *
     * @param id the value for hat_province.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.provinceID
     *
     * @return the value of hat_province.provinceID
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.provinceID
     *
     * @param provinceid the value for hat_province.provinceID
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hat_province.province
     *
     * @return the value of hat_province.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hat_province.province
     *
     * @param province the value for hat_province.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

	@Override
	public String toString() {
		return "HatProvince [id=" + id + ", provinceid=" + provinceid + ", province=" + province + "]";
	}
    
}