package com.sdey.api.po;

public class Lvfeimanager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lvfeimanager.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lvfeimanager.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lvfeimanager.psd
     *
     * @mbg.generated
     */
    private String psd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lvfeimanager.uid
     *
     * @return the value of lvfeimanager.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lvfeimanager.uid
     *
     * @param uid the value for lvfeimanager.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lvfeimanager.username
     *
     * @return the value of lvfeimanager.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lvfeimanager.username
     *
     * @param username the value for lvfeimanager.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lvfeimanager.psd
     *
     * @return the value of lvfeimanager.psd
     *
     * @mbg.generated
     */
    public String getPsd() {
        return psd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lvfeimanager.psd
     *
     * @param psd the value for lvfeimanager.psd
     *
     * @mbg.generated
     */
    public void setPsd(String psd) {
        this.psd = psd == null ? null : psd.trim();
    }
}