package com.sdey.api.po;

import java.util.Date;

public class Lvfeibaseinfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.uid
	 * @mbg.generated
	 */
	private Integer uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.username
	 * @mbg.generated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.sex
	 * @mbg.generated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.age
	 * @mbg.generated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.birthday
	 * @mbg.generated
	 */
	private Date birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.idcardnum
	 * @mbg.generated
	 */
	private String idcardnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.homeAddress_sheng
	 * @mbg.generated
	 */
	private String homeaddressSheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.homeAddress_shi
	 * @mbg.generated
	 */
	private String homeaddressShi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.homeAddress_qu
	 * @mbg.generated
	 */
	private String homeaddressQu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.homeAddress_display
	 * @mbg.generated
	 */
	private String homeaddressDisplay;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.homeAddress_xiangxi
	 * @mbg.generated
	 */
	private String homeaddressXiangxi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.phone
	 * @mbg.generated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.xiyanState
	 * @mbg.generated
	 */
	private Integer xiyanstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.xiyandaycount
	 * @mbg.generated
	 */
	private Integer xiyandaycount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.xiyanyearcount
	 * @mbg.generated
	 */
	private Float xiyanyearcount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.xiyanshi
	 * @mbg.generated
	 */
	private Float xiyanshi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jieyanState
	 * @mbg.generated
	 */
	private Integer jieyanstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jieyanyears
	 * @mbg.generated
	 */
	private Float jieyanyears;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.ershouyan
	 * @mbg.generated
	 */
	private Integer ershouyan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jiechuesyear
	 * @mbg.generated
	 */
	private Float jiechuesyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jiechuhuanjing
	 * @mbg.generated
	 */
	private Integer jiechuhuanjing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.zhiyeState
	 * @mbg.generated
	 */
	private Integer zhiyestate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.zhiyems
	 * @mbg.generated
	 */
	private String zhiyems;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.zhiyeyears
	 * @mbg.generated
	 */
	private Float zhiyeyears;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.wryState
	 * @mbg.generated
	 */
	private Integer wrystate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.wryjuzhuyears
	 * @mbg.generated
	 */
	private Float wryjuzhuyears;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.chufangSate
	 * @mbg.generated
	 */
	private Integer chufangsate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.cfyyqk
	 * @mbg.generated
	 */
	private Integer cfyyqk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.bingshiState
	 * @mbg.generated
	 */
	private Integer bingshistate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.bingshijb
	 * @mbg.generated
	 */
	private Integer bingshijb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.aizheng
	 * @mbg.generated
	 */
	private Integer aizheng;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.azjuti
	 * @mbg.generated
	 */
	private String azjuti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jiazushi
	 * @mbg.generated
	 */
	private Integer jiazushi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.jzsjuti
	 * @mbg.generated
	 */
	private String jzsjuti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.wryxiangxi
	 * @mbg.generated
	 */
	private Integer wryxiangxi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.bingshijbqt
	 * @mbg.generated
	 */
	private String bingshijbqt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lvfeibaseinfo.createTime
	 * @mbg.generated
	 */
	private Date createtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.uid
	 * @return  the value of lvfeibaseinfo.uid
	 * @mbg.generated
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.uid
	 * @param uid  the value for lvfeibaseinfo.uid
	 * @mbg.generated
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.username
	 * @return  the value of lvfeibaseinfo.username
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.username
	 * @param username  the value for lvfeibaseinfo.username
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.sex
	 * @return  the value of lvfeibaseinfo.sex
	 * @mbg.generated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.sex
	 * @param sex  the value for lvfeibaseinfo.sex
	 * @mbg.generated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.age
	 * @return  the value of lvfeibaseinfo.age
	 * @mbg.generated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.age
	 * @param age  the value for lvfeibaseinfo.age
	 * @mbg.generated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.birthday
	 * @return  the value of lvfeibaseinfo.birthday
	 * @mbg.generated
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.birthday
	 * @param birthday  the value for lvfeibaseinfo.birthday
	 * @mbg.generated
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.idcardnum
	 * @return  the value of lvfeibaseinfo.idcardnum
	 * @mbg.generated
	 */
	public String getIdcardnum() {
		return idcardnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.idcardnum
	 * @param idcardnum  the value for lvfeibaseinfo.idcardnum
	 * @mbg.generated
	 */
	public void setIdcardnum(String idcardnum) {
		this.idcardnum = idcardnum == null ? null : idcardnum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.homeAddress_sheng
	 * @return  the value of lvfeibaseinfo.homeAddress_sheng
	 * @mbg.generated
	 */
	public String getHomeaddressSheng() {
		return homeaddressSheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.homeAddress_sheng
	 * @param homeaddressSheng  the value for lvfeibaseinfo.homeAddress_sheng
	 * @mbg.generated
	 */
	public void setHomeaddressSheng(String homeaddressSheng) {
		this.homeaddressSheng = homeaddressSheng == null ? null : homeaddressSheng.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.homeAddress_shi
	 * @return  the value of lvfeibaseinfo.homeAddress_shi
	 * @mbg.generated
	 */
	public String getHomeaddressShi() {
		return homeaddressShi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.homeAddress_shi
	 * @param homeaddressShi  the value for lvfeibaseinfo.homeAddress_shi
	 * @mbg.generated
	 */
	public void setHomeaddressShi(String homeaddressShi) {
		this.homeaddressShi = homeaddressShi == null ? null : homeaddressShi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.homeAddress_qu
	 * @return  the value of lvfeibaseinfo.homeAddress_qu
	 * @mbg.generated
	 */
	public String getHomeaddressQu() {
		return homeaddressQu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.homeAddress_qu
	 * @param homeaddressQu  the value for lvfeibaseinfo.homeAddress_qu
	 * @mbg.generated
	 */
	public void setHomeaddressQu(String homeaddressQu) {
		this.homeaddressQu = homeaddressQu == null ? null : homeaddressQu.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.homeAddress_display
	 * @return  the value of lvfeibaseinfo.homeAddress_display
	 * @mbg.generated
	 */
	public String getHomeaddressDisplay() {
		return homeaddressDisplay;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.homeAddress_display
	 * @param homeaddressDisplay  the value for lvfeibaseinfo.homeAddress_display
	 * @mbg.generated
	 */
	public void setHomeaddressDisplay(String homeaddressDisplay) {
		this.homeaddressDisplay = homeaddressDisplay == null ? null : homeaddressDisplay.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.homeAddress_xiangxi
	 * @return  the value of lvfeibaseinfo.homeAddress_xiangxi
	 * @mbg.generated
	 */
	public String getHomeaddressXiangxi() {
		return homeaddressXiangxi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.homeAddress_xiangxi
	 * @param homeaddressXiangxi  the value for lvfeibaseinfo.homeAddress_xiangxi
	 * @mbg.generated
	 */
	public void setHomeaddressXiangxi(String homeaddressXiangxi) {
		this.homeaddressXiangxi = homeaddressXiangxi == null ? null : homeaddressXiangxi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.phone
	 * @return  the value of lvfeibaseinfo.phone
	 * @mbg.generated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.phone
	 * @param phone  the value for lvfeibaseinfo.phone
	 * @mbg.generated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.xiyanState
	 * @return  the value of lvfeibaseinfo.xiyanState
	 * @mbg.generated
	 */
	public Integer getXiyanstate() {
		return xiyanstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.xiyanState
	 * @param xiyanstate  the value for lvfeibaseinfo.xiyanState
	 * @mbg.generated
	 */
	public void setXiyanstate(Integer xiyanstate) {
		this.xiyanstate = xiyanstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.xiyandaycount
	 * @return  the value of lvfeibaseinfo.xiyandaycount
	 * @mbg.generated
	 */
	public Integer getXiyandaycount() {
		return xiyandaycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.xiyandaycount
	 * @param xiyandaycount  the value for lvfeibaseinfo.xiyandaycount
	 * @mbg.generated
	 */
	public void setXiyandaycount(Integer xiyandaycount) {
		this.xiyandaycount = xiyandaycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.xiyanyearcount
	 * @return  the value of lvfeibaseinfo.xiyanyearcount
	 * @mbg.generated
	 */
	public Float getXiyanyearcount() {
		return xiyanyearcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.xiyanyearcount
	 * @param xiyanyearcount  the value for lvfeibaseinfo.xiyanyearcount
	 * @mbg.generated
	 */
	public void setXiyanyearcount(Float xiyanyearcount) {
		this.xiyanyearcount = xiyanyearcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.xiyanshi
	 * @return  the value of lvfeibaseinfo.xiyanshi
	 * @mbg.generated
	 */
	public Float getXiyanshi() {
		return xiyanshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.xiyanshi
	 * @param xiyanshi  the value for lvfeibaseinfo.xiyanshi
	 * @mbg.generated
	 */
	public void setXiyanshi(Float xiyanshi) {
		this.xiyanshi = xiyanshi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jieyanState
	 * @return  the value of lvfeibaseinfo.jieyanState
	 * @mbg.generated
	 */
	public Integer getJieyanstate() {
		return jieyanstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jieyanState
	 * @param jieyanstate  the value for lvfeibaseinfo.jieyanState
	 * @mbg.generated
	 */
	public void setJieyanstate(Integer jieyanstate) {
		this.jieyanstate = jieyanstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jieyanyears
	 * @return  the value of lvfeibaseinfo.jieyanyears
	 * @mbg.generated
	 */
	public Float getJieyanyears() {
		return jieyanyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jieyanyears
	 * @param jieyanyears  the value for lvfeibaseinfo.jieyanyears
	 * @mbg.generated
	 */
	public void setJieyanyears(Float jieyanyears) {
		this.jieyanyears = jieyanyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.ershouyan
	 * @return  the value of lvfeibaseinfo.ershouyan
	 * @mbg.generated
	 */
	public Integer getErshouyan() {
		return ershouyan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.ershouyan
	 * @param ershouyan  the value for lvfeibaseinfo.ershouyan
	 * @mbg.generated
	 */
	public void setErshouyan(Integer ershouyan) {
		this.ershouyan = ershouyan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jiechuesyear
	 * @return  the value of lvfeibaseinfo.jiechuesyear
	 * @mbg.generated
	 */
	public Float getJiechuesyear() {
		return jiechuesyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jiechuesyear
	 * @param jiechuesyear  the value for lvfeibaseinfo.jiechuesyear
	 * @mbg.generated
	 */
	public void setJiechuesyear(Float jiechuesyear) {
		this.jiechuesyear = jiechuesyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jiechuhuanjing
	 * @return  the value of lvfeibaseinfo.jiechuhuanjing
	 * @mbg.generated
	 */
	public Integer getJiechuhuanjing() {
		return jiechuhuanjing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jiechuhuanjing
	 * @param jiechuhuanjing  the value for lvfeibaseinfo.jiechuhuanjing
	 * @mbg.generated
	 */
	public void setJiechuhuanjing(Integer jiechuhuanjing) {
		this.jiechuhuanjing = jiechuhuanjing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.zhiyeState
	 * @return  the value of lvfeibaseinfo.zhiyeState
	 * @mbg.generated
	 */
	public Integer getZhiyestate() {
		return zhiyestate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.zhiyeState
	 * @param zhiyestate  the value for lvfeibaseinfo.zhiyeState
	 * @mbg.generated
	 */
	public void setZhiyestate(Integer zhiyestate) {
		this.zhiyestate = zhiyestate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.zhiyems
	 * @return  the value of lvfeibaseinfo.zhiyems
	 * @mbg.generated
	 */
	public String getZhiyems() {
		return zhiyems;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.zhiyems
	 * @param zhiyems  the value for lvfeibaseinfo.zhiyems
	 * @mbg.generated
	 */
	public void setZhiyems(String zhiyems) {
		this.zhiyems = zhiyems == null ? null : zhiyems.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.zhiyeyears
	 * @return  the value of lvfeibaseinfo.zhiyeyears
	 * @mbg.generated
	 */
	public Float getZhiyeyears() {
		return zhiyeyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.zhiyeyears
	 * @param zhiyeyears  the value for lvfeibaseinfo.zhiyeyears
	 * @mbg.generated
	 */
	public void setZhiyeyears(Float zhiyeyears) {
		this.zhiyeyears = zhiyeyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.wryState
	 * @return  the value of lvfeibaseinfo.wryState
	 * @mbg.generated
	 */
	public Integer getWrystate() {
		return wrystate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.wryState
	 * @param wrystate  the value for lvfeibaseinfo.wryState
	 * @mbg.generated
	 */
	public void setWrystate(Integer wrystate) {
		this.wrystate = wrystate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.wryjuzhuyears
	 * @return  the value of lvfeibaseinfo.wryjuzhuyears
	 * @mbg.generated
	 */
	public Float getWryjuzhuyears() {
		return wryjuzhuyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.wryjuzhuyears
	 * @param wryjuzhuyears  the value for lvfeibaseinfo.wryjuzhuyears
	 * @mbg.generated
	 */
	public void setWryjuzhuyears(Float wryjuzhuyears) {
		this.wryjuzhuyears = wryjuzhuyears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.chufangSate
	 * @return  the value of lvfeibaseinfo.chufangSate
	 * @mbg.generated
	 */
	public Integer getChufangsate() {
		return chufangsate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.chufangSate
	 * @param chufangsate  the value for lvfeibaseinfo.chufangSate
	 * @mbg.generated
	 */
	public void setChufangsate(Integer chufangsate) {
		this.chufangsate = chufangsate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.cfyyqk
	 * @return  the value of lvfeibaseinfo.cfyyqk
	 * @mbg.generated
	 */
	public Integer getCfyyqk() {
		return cfyyqk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.cfyyqk
	 * @param cfyyqk  the value for lvfeibaseinfo.cfyyqk
	 * @mbg.generated
	 */
	public void setCfyyqk(Integer cfyyqk) {
		this.cfyyqk = cfyyqk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.bingshiState
	 * @return  the value of lvfeibaseinfo.bingshiState
	 * @mbg.generated
	 */
	public Integer getBingshistate() {
		return bingshistate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.bingshiState
	 * @param bingshistate  the value for lvfeibaseinfo.bingshiState
	 * @mbg.generated
	 */
	public void setBingshistate(Integer bingshistate) {
		this.bingshistate = bingshistate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.bingshijb
	 * @return  the value of lvfeibaseinfo.bingshijb
	 * @mbg.generated
	 */
	public Integer getBingshijb() {
		return bingshijb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.bingshijb
	 * @param bingshijb  the value for lvfeibaseinfo.bingshijb
	 * @mbg.generated
	 */
	public void setBingshijb(Integer bingshijb) {
		this.bingshijb = bingshijb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.aizheng
	 * @return  the value of lvfeibaseinfo.aizheng
	 * @mbg.generated
	 */
	public Integer getAizheng() {
		return aizheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.aizheng
	 * @param aizheng  the value for lvfeibaseinfo.aizheng
	 * @mbg.generated
	 */
	public void setAizheng(Integer aizheng) {
		this.aizheng = aizheng;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.azjuti
	 * @return  the value of lvfeibaseinfo.azjuti
	 * @mbg.generated
	 */
	public String getAzjuti() {
		return azjuti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.azjuti
	 * @param azjuti  the value for lvfeibaseinfo.azjuti
	 * @mbg.generated
	 */
	public void setAzjuti(String azjuti) {
		this.azjuti = azjuti == null ? null : azjuti.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jiazushi
	 * @return  the value of lvfeibaseinfo.jiazushi
	 * @mbg.generated
	 */
	public Integer getJiazushi() {
		return jiazushi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jiazushi
	 * @param jiazushi  the value for lvfeibaseinfo.jiazushi
	 * @mbg.generated
	 */
	public void setJiazushi(Integer jiazushi) {
		this.jiazushi = jiazushi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.jzsjuti
	 * @return  the value of lvfeibaseinfo.jzsjuti
	 * @mbg.generated
	 */
	public String getJzsjuti() {
		return jzsjuti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.jzsjuti
	 * @param jzsjuti  the value for lvfeibaseinfo.jzsjuti
	 * @mbg.generated
	 */
	public void setJzsjuti(String jzsjuti) {
		this.jzsjuti = jzsjuti == null ? null : jzsjuti.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.wryxiangxi
	 * @return  the value of lvfeibaseinfo.wryxiangxi
	 * @mbg.generated
	 */
	public Integer getWryxiangxi() {
		return wryxiangxi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.wryxiangxi
	 * @param wryxiangxi  the value for lvfeibaseinfo.wryxiangxi
	 * @mbg.generated
	 */
	public void setWryxiangxi(Integer wryxiangxi) {
		this.wryxiangxi = wryxiangxi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.bingshijbqt
	 * @return  the value of lvfeibaseinfo.bingshijbqt
	 * @mbg.generated
	 */
	public String getBingshijbqt() {
		return bingshijbqt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.bingshijbqt
	 * @param bingshijbqt  the value for lvfeibaseinfo.bingshijbqt
	 * @mbg.generated
	 */
	public void setBingshijbqt(String bingshijbqt) {
		this.bingshijbqt = bingshijbqt == null ? null : bingshijbqt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lvfeibaseinfo.createTime
	 * @return  the value of lvfeibaseinfo.createTime
	 * @mbg.generated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lvfeibaseinfo.createTime
	 * @param createtime  the value for lvfeibaseinfo.createTime
	 * @mbg.generated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Override
	public String toString() {
		return "Lvfeibaseinfo [uid=" + uid + ", username=" + username + ", sex=" + sex + ", age=" + age + ", birthday="
				+ birthday + ", idcardnum=" + idcardnum + ", homeaddressSheng=" + homeaddressSheng + ", homeaddressShi="
				+ homeaddressShi + ", homeaddressQu=" + homeaddressQu + ", homeaddressDisplay=" + homeaddressDisplay
				+ ", homeaddressXiangxi=" + homeaddressXiangxi + ", phone=" + phone + ", xiyanstate=" + xiyanstate
				+ ", xiyandaycount=" + xiyandaycount + ", xiyanyearcount=" + xiyanyearcount + ", xiyanshi=" + xiyanshi
				+ ", jieyanstate=" + jieyanstate + ", jieyanyears=" + jieyanyears + ", ershouyan=" + ershouyan
				+ ", jiechuesyear=" + jiechuesyear + ", jiechuhuanjing=" + jiechuhuanjing + ", zhiyestate=" + zhiyestate
				+ ", zhiyems=" + zhiyems + ", zhiyeyears=" + zhiyeyears + ", wrystate=" + wrystate + ", wryjuzhuyears="
				+ wryjuzhuyears + ", chufangsate=" + chufangsate + ", cfyyqk=" + cfyyqk + ", bingshistate="
				+ bingshistate + ", bingshijb=" + bingshijb + ", aizheng=" + aizheng + ", azjuti=" + azjuti
				+ ", jiazushi=" + jiazushi + ", jzsjuti=" + jzsjuti + ", wryxiangxi=" + wryxiangxi + ", bingshijbqt="
				+ bingshijbqt + "]";
	}
	
}